name: Code Quality

on:
  pull_request:
    branches: [master, main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root

      - name: Run isort
        run: |
          poetry run isort . --check-only --diff

      - name: Run Black
        run: |
          poetry run black --check .

      - name: Run Flake8
        run: |
          poetry run flake8 .
